USE [master]
GO

/****** Object:  Database [ProjetoTesteWebApi]    Script Date: 23/06/2020 16:28:25 ******/
CREATE DATABASE [ProjetoTesteWebApi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProjetoTesteWebApi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ProjetoTesteWebApi.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ProjetoTesteWebApi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ProjetoTesteWebApi_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ProjetoTesteWebApi] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProjetoTesteWebApi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProjetoTesteWebApi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET  MULTI_USER 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProjetoTesteWebApi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProjetoTesteWebApi] SET  READ_WRITE 
GO


